export const TRANSACTION_CATEGORIES = [
  "Mercado",
  "Transporte",
  "Moradia",
  "Alimentação",
  "Lazer",
  "Tecnologia",
  "Saúde",
  "Educação",
  "Salário",
  "Assinaturas",
  "Pets",
  "Viagem",
  "Outros",
] as const;
